name: Warrantly-WarrantyTracker
options:
  bundleIdPrefix: com.shimondeitel.warrantly
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Warrantly-WarrantyTracker:
    type: application
    platform: iOS
    sources:
      - path: Warrantly-WarrantyTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.warrantly
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Warrantly-WarrantyTracker/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Warrantly-WarrantyTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Warrantly-WarrantyTrackerTests
      - path: Warrantly-WarrantyTracker.storekit
    dependencies:
      - target: Warrantly-WarrantyTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.warrantly.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Warrantly-WarrantyTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Warrantly-WarrantyTrackerUITests
    dependencies:
      - target: Warrantly-WarrantyTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.warrantly.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Warrantly-WarrantyTracker:
    build:
      targets:
        Warrantly-WarrantyTracker: all
        Warrantly-WarrantyTrackerTests: [test]
        Warrantly-WarrantyTrackerUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Warrantly-WarrantyTracker.storekit
    test:
      config: Debug
      storeKitConfiguration: Warrantly-WarrantyTracker.storekit
      targets:
        - Warrantly-WarrantyTrackerTests
        - Warrantly-WarrantyTrackerUITests
    archive:
      config: Release
